name: Releases

on: 
  push:
    branches:
      ["dev"]
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Version or Commit SHA
      uses: hsblhsn/version-or-commit-sha@v1.0.1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "README.md"
        commit: "dev"
        body: "Test"
        
        
