name: Releases

on: 
  push:
    branches:
      ["dev"]
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "README.md"
        body: "Test"
